let l1 = {id:"1", tag: "du lich", tittle: "Quần đảo Cook - thiên đường du lịch nhiệt đới Nam Thái Bình Dương", img:"../data/daocook8.png", link: "../html/daocook.html", content: "Nổi tiếng với những hòn đảo xinh đẹp, nước biển màu ngọc lam cùng vô vàn hoạt động giải trí và văn hóa lâu đời, không khó hiểu khi ngành du lịch chiếm trên 65% GDP quốc gia quần đảo này." };
let l2 = {id:"2", tag: "viet nam", tittle: "Bộ Chính trị tổ chức hội nghị về phát triển đồng bằng sông Cửu Long", img:"../data/npt.jpg", link: "../html/baiviet1.html", content: "Hội nghị toàn quốc quán triệt, triển khai nghị quyết mới của Bộ Chính trị về phát triển kinh tế - xã hội, bảo đảm quốc phòng, an ninh vùng đồng bằng sông Cửu Long đến năm 2030, tầm nhìn đến năm 2045 đã khai mạc sáng 22.4." };
let l3 = {id:"3", tag: "review san pham", tittle: "Đánh giá TUF Dash F15: “Bạch quỷ chốn thiên đường” trong giới game thủ", img:"../data/baiviet2-1.jpg", link: "../html/baiviet2.html", content: "Qua rồi cái thời laptop gaming được tạo ra chỉ với một sứ mệnh duy nhất, đó là chơi game. Ngày nay, khi các môn học càng trở nên đa dạng, ngành nghề cũng phát triển theo nhiều chiều hướng khác nhau, các bạn sinh viên cũng phải thích nghi liên tục để phù hợp với công việc và xu hướng của thời đại 4.0." };
let l4 = {id:"4", tag: "thu thuat meo hay", tittle: "Nếu sở hữu tài sản khổng lồ của Elon Musk thì đây những gì mà bạn sẽ mua được", img:"../data/baiviet3-1.jpg", link: "../html/baiviet3.html", content: "Elon Musk là siêu tỷ phú giàu nhất thế giới hiện nay với mức tài sản vô cùng khổng lồ. Các bạn đã bao giờ nhìn vô con số đó và tự hỏi rằng nếu có trong tay số tài sản của Elon Musk thì bạn sẽ mua được những gì chưa? " };
let l5 = {id:"5", tag: "cong nghe 24h", tittle: "Lộ tin cấu hình tăng tốc RAM của AMD sẽ có tên chính thức là EXPO", img:"../data/baiviet4-1.jpg", link: "../html/baiviet4.html", content: "Cách đây hơn 3 tháng, một số thông tin rò rỉ đã cho chúng ta biết rằng AMD đã lên kế hoạch cho ra mắt bộ cấu hình tăng tốc RAM tương tự như XMP của Intel, được gọi là Ryzen Accelerated Memory Profile (RAMP)." };
let l6 = {id: "6", tag: "thu thuat meo hay", tittle: "Mời các bạn thử tài phối nhạc với ứng dụng Incredibox siêu chất, cẩn thận chơi là ghiền", img: "../data/baiviet5-1.jpg",link: "../html/baiviet5.html" ,content: "Incredibox là một ứng dụng âm nhạc cho phép bạn có thể nhanh chóng tạo ra một bản phối bằng cách điều khiển một dàn beatboxer. Ứng dụng rất hay và sáng tạo, thích hợp với những bạn nào thích âm nhạc, và thích sáng tác ra các ca khúc của riêng mình."};
let l7 = {id: "7", tag: "cong nghe 24h", tittle: "Số tiền 21 tỉ để mua Twitter của Elon Musk ở đâu ra?", img: "../data/baiviet6-1.jpeg",link: "../html/baiviet6.html" , content: "Lời đề nghị mua lại Twitter của tỉ phú Elon Musk yêu cầu anh ta phải trang trải phần vốn chủ sở hữu 21 tỉ USD từ nguồn tiền cá nhân. Vậy Musk 'đào' đâu ra số tiền này?"};
let l8 = {id: "8", tag: "quoc te", tittle: "Nga nói kiểm soát toàn bộ vùng Kherson, đưa ra cảnh báo Anh", img: "../data/baiviet7-1.jpg",link: "../html/baiviet7.html" , content: "Rạng sáng 27.4, Bộ Quốc phòng Nga tuyên bố Nga đã kiểm soát toàn bộ tỉnh Kherson ở miền nam Ukraine, đồng thời chỉ định người đứng đầu thủ phủ vùng này."};
let l9 = {id: "9", tag: "quoc te", tittle: "Ngoại trưởng Nga nói gì về nguy cơ xảy ra Thế chiến 3?", img: "../data/baiviet8-1.jpg",link: "../html/baiviet8.html" , content: "Ngoại trưởng Nga Sergei Lavrov hôm 25.4 nói lập trường của Nga là không thể chấp nhận chiến tranh hạt nhân, nhưng tình hình đã xấu đi đến mức có nguy cơ thật sự sẽ xảy ra một cuộc chiến như vậy."};
let l10 = {id: "10", tag: "quoc te", tittle: "Pakistan: Nữ sinh đánh bom liều chết, 3 giảng viên Trung Quốc thiệt mạng", img: "../data/baiviet10-1.webp",link: "../html/baiviet10.html" , content: "3 giảng viên người Trung Quốc thiệt mạng trong vụ đánh bom liều chết tại trường ĐH Karachi, Pakistan, hôm 26-4."};
let l11 = {id: "11", tag: "truyen hinh", tittle: "Eighteen Again: Phim gia đình xúc động về 'ông bố tuổi teen', thêm dàn cast đẹp chói lòa còn xem là còn mê", img: "../data/baiviet9-1.webp",link: "../html/baiviet9.html" , content: "Eighteen Again (18 Again) với sự tham gia của Kim Ha Neul, Yoon Sang Hyun và Lee Do Hyun đang nhận được nhiều sự yêu mến của khán giả."};
let l12 = {id: "12", tag: "viet nam", tittle: "Khánh thành cầu Thủ Thiêm 2", img: "../data/baiviet111.jpg",link: "../html/baiviet11.html" , content: "Ngày 28/4, cầu Thủ Thiêm 2 dài gần 1,5 km, 6 làn xe, bắc qua sông Sài Gòn, được xem là biểu tượng mới của TP HCM, được thông xe sau 7 năm triển khai."};
let l13 = {id: "13", tag: "bong da quoc te", tittle: "Benzema: 'Real sẽ thắng Man City ở lượt về'", img: "../data/baiviet121.jpg",link: "../html/baiviet12.html" , content: "Tiền đạo chủ lực của Real Karim Benzema tự tin sẽ đánh bại Man City ở bán kết lượt về để vào chung kết Champions League"};
let l14 = {id: "14", tag: "am nhac", tittle: "Sơn Tùng M-TP lần đầu ra ca khúc tiếng Anh", img: "../data/baiviet131.jpg",link: "../html/baiviet13.html" , content: "Ca sĩ Sơn Tùng M-TP trở lại làng nhạc sau một năm với ca khúc tiếng Anh There's No One At All, sẽ phát hành ngày 28/4."};
let l15 = {id: "15", tag: "san pham moi", tittle: "Băng gạc điện diệt vi khuẩn gây hại ở vết thương", img: "../data/baiviet141.jpg",link: "../html/baiviet14.html" , content: "MỸ - Các nhà nghiên cứu tìm ra cách ứng dụng điện để chữa lành vết thương, giúp thúc đẩy quá trình hồi phục bằng cách tiêu diệt vi khuẩn."};
let l16 = {id: "16", tag: "am thuc", tittle: "Món sashimi 'thuận buồm xuôi gió'", img: "../data/baiviet151.jpg",link: "../html/baiviet15.html" , content: "Trong lễ ra mắt Chi hội Đầu bếp Hà Nội (VICA Hà Nội) tối 24/4, thực khách và các đầu bếp nổi tiếng được chứng kiến màn trình diễn chế biến sashimi cá bơn vàng. Đây là món ăn có tên gọi 'Thuận buồm xuôi gió', được giới kinh doanh yêu thích do có nhiều ý nghĩa về sự thịnh vượng và khởi đầu thuận lợi."};
let l17 = {id: "17", tag: "tuyen sinh", tittle: "Học viện Hàng không Việt Nam mở bốn ngành mới", img: "../data/baiviet161.jpg",link: "../html/baiviet16.html" , content: "Năm 2022, Học viện Hàng không Việt Nam tuyển sinh 11 ngành với tổng chỉ tiêu 2.120, trong đó có bốn ngành lần đầu đào tạo."};
let l18 = {id: "18", tag: "am thuc", tittle: "Bánh hạt dẻ vạn người mê ở Sa Pa", img: "../data/baiviet171.jpg",link: "../html/baiviet17.html" , content: "LÀO CAI - Những chiếc bánh hạt dẻ nóng, thơm phức là thứ khiến nhiều thực khách phải nán lại mỗi lần đi chợ vùng cao."};
let l19 = {id: "19", tag: "du lich", tittle: "Yêu đời hơn sau chuyến xuyên Việt 22 ngày", img: "../data/baiviet181.jpg",link: "../html/baiviet18.html" , content: "'Hơn cả một hành trình' là những gì mà Phạm Trang, sinh năm 1999, nói về chuyến xuyên Việt sau khi tốt nghiệp đại học. Cô cùng hai người bạn là Lê Giang, bằng tuổi, và Trương Đình Minh, sinh năm 1997 trên hai chiếc xe máy, rong ruổi khắp Việt Nam từ ngày 28/2 đến 20/3, cùng nhau trải qua một tuổi trẻ ý nghĩa."};
let l20 = {id: "20", tag: "bac si online", tittle: "Trầm cảm tuổi vị thành niên dưới góc nhìn đa chiều", img: "../data/baiviet191.jpg",link: "../html/baiviet19.html" , content: "Những con người thật, chuyện thật về góc khuất và tác động của trầm cảm tuổi vị thành niên sẽ được chia sẻ trong 6 vieo trên eBox, lên sóng 16/5."};
let l21 = {id: "21", tag: "doanh nhan", tittle: "Hội Doanh nhân trẻ Việt Nam: Tiên phong đổi mới để kiến tạo giá trị", img: "../data/baiviet201.jpg",link: "../html/baiviet20.html" , content: "Đại hội Hội Doanh nhân trẻ Việt Nam khóa VII vừa hiệp thương, chọn cử ông Đặng Hồng Anh tiếp tục giữ chức Chủ tịch Hội doanh nhân trẻ Việt Nam khóa VII, nhiệm kỳ 2022 - 2025."};
let l22 = {id: "22", tag: "bong chuyen", tittle: "Fenerbahçe gia hạn hợp đồng với chuyền 2 huyền thoại của Iran", img: "../data/baiviet21-1.jpg",link: "../html/baiviet21.html" , content: "Sau khi kết thúc Olympic Tokyo 2020, Saeid Marouf đã trải qua một thời gian 6 tháng không thi đấu. Chuyền hai người Iran ký hợp đồng với CLB Bắc Kinh, nhưng do giải đấu liên tục bị trì hoãn bởi dịch COVID-19, Marouf phải tìm kiếm một bến đỗ khác và anh đã gia nhập Fenerbahçe.S.K vào tháng 1 năm nay."};
let l23 = {id: "23", tag: "quoc te", tittle: "Ukraine xin lỗi Nhật Bản vì so sánh Nhật hoàng Hirohito với Hitler", img: "../data/adolfhitler.jpg",link: "../html/ukraine.html" , content: "Trong thông báo đăng trên mạng xã hội Twitter, Chính phủ Ukraine đã lên tiếng xin lỗi Nhật Bản sau một video so sánh Nhật hoàng Hirohito với trùm phát xít Đức Adolf Hitler."};


/* Them nua */
/* let l24 = {id: "24", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l25 = {id: "25", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l26 = {id: "26", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l27 = {id: "27", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l28 = {id: "28", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l29 = {id: "29", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};
let l30 = {id: "30", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""}; */
//let l = {id: "", tag: "", tittle: "", img: "../data/",link: "../html/baiviet.html" , content: ""};

var datapagination = [l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21, l22, l23/* , l24, l25, l26, l27, l28, l29, l30 */];